# This file is part of PSGopher.
#
# PSGopher is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# PSGopher is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with PSGopher. If not, see <https://www.gnu.org/licenses/>. 

name: Run Pester tests
on: push

jobs:
  pester-test-pwsh:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name:  Check out repository
        uses:  actions/checkout@v3
      - name:  Run Pester tests (PowerShell)
        shell: pwsh
        run:   |
          Write-Output "Testing with $($PSVersionTable.PSVersion)."
          Set-PSRepository 'PSGallery' -InstallationPolicy 'Trusted'
          Install-Module -Name 'Pester' -Confirm:$false -Force
          Invoke-Pester -Name 'PSGopher.Tests.ps1' -PassThru
